var PLAYER=PLAYER||{};
PLAYER.Vast=function(b){this.videoPlayer=b;this.options=this.videoPlayer.options;this.vastObj={};this.objVMAP;this.arrVAST=[];this.vastADCount=this.maxcountXMLS=this.countXMLS=this.countVasts=0;this.allVastMediaFilesArr=[];this.allVastNonLinearArr=[];this.allVastCompanionArr=[];this.is_VMAP=this.is_VAST=!1;this.allVastPREROLLS={};this.prerollsCount=0;this.allVastMIDROLLS={};this.midrollsCount=0;this.allVastPOSTROLLS={};this.postrollsCount=0;this.allVastNONLINEARS={};this.nonlinearsCount=0;""!=this.options.vastUrl&&
this.loadVastUrl(this.options.vastUrl)};PLAYER.Vast.prototype={};
PLAYER.Vast.prototype.loadVastUrl=function(b,d){var a=this;jQuery.ajax({type:"GET",url:b,dataType:"xml",success:function(c){a.linear=jQuery(c).find("Linear").text();a.nonLinear=jQuery(c).find("NonLinearAds").text();var e=a.xmlToJson(c);a.vast_array=[];jQuery(c).find("Ad").each(function(f){f=jQuery(this).attr("id");jQuery(this).attr("offset");jQuery(this).find("InLine").each(function(){var n=jQuery(this).find("AdSystem").text(),p=jQuery(this).find("AdTitle").text(),q=jQuery(this).find("Description").text(),
r=jQuery(this).find("Error").text(),t=jQuery(this).find("Impression").text();jQuery(this).find("Creatives").text();a.creative={};jQuery(this).find("Creatives").each(function(){jQuery(this).find("Creative").each(function(k){var l=jQuery(this).attr("id"),m=jQuery(this).attr("sequence");jQuery(this).find("Linear").each(function(){a.duration={};a.trackingEvents={};a.videoClicks={};a.mediaFiles={};jQuery(this).find("Duration").each(function(){a.duration=jQuery(this).text()});a.trackingEvents={};jQuery(this).find("TrackingEvents").each(function(){a.tracking=
{};jQuery(this).find("Tracking").each(function(){var g=jQuery(this).attr("event"),h=jQuery(this).text();a.tracking[g]={event:g,tracking:h}});a.trackingEvents={tracking:a.tracking}});a.videoClicks={};jQuery(this).find("VideoClicks").each(function(){jQuery(this).find("ClickThrough").each(function(){a.clickThrough=jQuery(this).text()});a.videoClicks={clickThrough:a.clickThrough}});a.mediaFiles={};jQuery(this).find("MediaFiles").each(function(){jQuery(this).find("MediaFile").each(function(){a.mediaFile=
jQuery(this).text()});a.mediaFiles={mediaFiles:a.mediaFile}});a.linear={duration:a.duration,trackingEvents:a.trackingEvents,videoClicks:a.videoClicks,mediaFiles:a.mediaFiles}});jQuery(this).find("NonLinearAds").each(function(){a.trackingEvents={};a.nonLinear={};jQuery(this).find("TrackingEvents").each(function(){a.tracking={};jQuery(this).find("Tracking").each(function(){var g=jQuery(this).attr("event"),h=jQuery(this).text();a.tracking[g]={event:g,tracking:h}});a.trackingEvents={tracking:a.tracking}});
jQuery(this).find("NonLinear").each(function(){a.staticResource={};jQuery(this).find("StaticResource").each(function(){var g=jQuery(this).attr("creativeType"),h=jQuery(this).text();a.staticResource={creativeType:g,staticResource:h}});jQuery(this).find("NonLinearClickThrough").each(function(){a.nonLinearClickThrough=jQuery(this).text()});jQuery(this).find("NonLinearClickTracking").each(function(){a.nonLinearClickTracking=jQuery(this).text()});a.nonLinear={staticResource:a.staticResource,nonLinearClickThrough:a.nonLinearClickThrough,
nonLinearClickTracking:a.nonLinearClickTracking}});a.nonLinearAds={trackingEvents:a.trackingEvents,nonLinear:a.nonLinear}});0<jQuery(this).find("Linear").length&&(a.creative[k]={id:l,sequence:m,linear:a.linear});0<jQuery(this).find("NonLinearAds").length&&(a.creative[k]={id:l,sequence:m,nonLinearAds:a.nonLinearAds})});a.Creatives={Creative:a.creative}});a.InLine={AdSystem:n,AdTitle:p,Description:q,Error:r,Impression:t,Creatives:a.Creatives}});a.ad={id:f,InLine:a.InLine};a.vast_array.push(a.ad)});
a.handleLoadedXML(e,d)}})};
PLAYER.Vast.prototype.xmlToJson=function(b){var d={};if(1==b.nodeType){if(0<b.attributes.length){d["@attributes"]={};for(var a=0;a<b.attributes.length;a++){var c=b.attributes.item(a);d["@attributes"][c.nodeName]=c.nodeValue}}}else 3==b.nodeType?d=b.nodeValue.trim():4==b.nodeType&&(d=b.nodeValue);if(b.hasChildNodes())for(a=0;a<b.childNodes.length;a++){c=b.childNodes.item(a);var e=c.nodeName;if("undefined"==typeof d[e])d[e]=this.xmlToJson(c);else{if("undefined"==typeof d[e].length){var f=d[e];d[e]=
[];d[e].push(f)}"object"===typeof d[e]&&d[e].push(this.xmlToJson(c))}}return d};PLAYER.Vast.prototype.convertTimeStringToSeconds=function(b){if(!b||!b.match(/^(\d){2}(:[0-5][0-9]){2}(.(\d){1,3})?$/))return!1;b=b.split(":");return 3600*parseInt(b[0],10)+60*parseInt(b[1],10)+parseInt(b[2],10)};
PLAYER.Vast.prototype.handleLoadedXML=function(b,d){this.countXMLS++;if("undefined"!==typeof b["vmap:VMAP"]){this.is_VMAP=!0;this.objVMAP=b;b["vmap:VMAP"]["vmap:AdBreak"].length||(b["vmap:VMAP"]["vmap:AdBreak"]=[b["vmap:VMAP"]["vmap:AdBreak"]]);this.maxcountXMLS=1;for(var a=0;a<b["vmap:VMAP"]["vmap:AdBreak"].length;a++)this.countVasts++,this.maxcountXMLS++,this.loadVastUrl(b["vmap:VMAP"]["vmap:AdBreak"][a]["vmap:AdSource"]["vmap:AdTagURI"]["#cdata-section"],b["vmap:VMAP"]["vmap:AdBreak"][a]["@attributes"].timeOffset)}if("undefined"!==
typeof b.VAST){0==this.countVasts?(this.vastObj[0]=b,this.maxcountXMLS=1,this.is_VAST=!0):0<this.countVasts&&this.arrVAST.push(b);if(void 0==b.VAST.Ad){alert("No <Ad> tag found in VAST url. Try refreshing the page.");return}b.VAST.Ad.length||(b.VAST.Ad=[b.VAST.Ad]);for(a=0;a<b.VAST.Ad.length;a++){d&&this.is_VMAP&&(b.VAST.Ad[a]["@attributes"].timeOffset=d);void 0!==b.VAST.Ad[a]["@attributes"].timeOffset&&(d=b.VAST.Ad[a]["@attributes"].timeOffset);b.VAST.Ad[a].InLine.Creatives.Creative.length||(b.VAST.Ad[a].InLine.Creatives.Creative=
[b.VAST.Ad[a].InLine.Creatives.Creative]);for(var c=0;c<b.VAST.Ad[a].InLine.Creatives.Creative.length;c++){b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear&&(b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear.MediaFiles.MediaFile.length||(b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear.MediaFiles.MediaFile=[b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear.MediaFiles.MediaFile]),this.allVastMediaFilesArr.push(b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear.MediaFiles.MediaFile[0]["#cdata-section"]),
this.clickThrough=b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear.VideoClicks.ClickThrough["#cdata-section"],this.mediaFile=b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear.MediaFiles.MediaFile[0]["#cdata-section"],b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear.hasOwnProperty("@attributes")&&(this.skipoffset=b.VAST.Ad[a].InLine.Creatives.Creative[c].Linear["@attributes"].skipoffset),this.is_VMAP?this.handleROLLS(d,"linear"):void 0!==b.VAST.Ad[a]["@attributes"].timeOffset?this.handleROLLS(d,"linear"):
(this.allVastPREROLLS[this.prerollsCount]={mediaFile:this.mediaFile,clickThrough:this.clickThrough,skipoffset:this.skipoffset},this.prerollsCount++));if(b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds){b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear.length||(b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear=[b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear]);for(var e=0;e<b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear.length;e++){b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].StaticResource.length||
(b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].StaticResource=[b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].StaticResource]);this.minSuggestedDuration=b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e]["@attributes"].minSuggestedDuration;for(var f=0;f<b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].StaticResource.length;f++)this.allVastNonLinearArr.push(b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].StaticResource[f]["#cdata-section"]);
this.nonLinearClickThrough=b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].NonLinearClickThrough["#cdata-section"];this.nonLinearClickTracking=b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].NonLinearClickTracking["#cdata-section"];this.staticResource=b.VAST.Ad[a].InLine.Creatives.Creative[c].NonLinearAds.NonLinear[e].StaticResource[0]["#cdata-section"];this.handleROLLS(d,"nonlinear")}}b.VAST.Ad[a].InLine.Creatives.Creative[c].CompanionAds&&(b.VAST.Ad[a].InLine.Creatives.Creative[c].CompanionAds.Companion.length||
(b.VAST.Ad[a].InLine.Creatives.Creative[c].CompanionAds.Companion=[b.VAST.Ad[a].InLine.Creatives.Creative[c].CompanionAds.Companion]),this.allVastCompanionArr.push(b.VAST.Ad[a].InLine.Creatives.Creative[c].CompanionAds.Companion[0].StaticResource["#cdata-section"]))}}}this.countXMLS==this.maxcountXMLS&&this.initData()};
PLAYER.Vast.prototype.handleROLLS=function(b,d){"start"==b&&(this.allVastPREROLLS[this.prerollsCount]={mediaFile:this.mediaFile,clickThrough:this.clickThrough,skipoffset:this.skipoffset},this.prerollsCount++);"end"==b&&(this.allVastPOSTROLLS[this.postrollsCount]={mediaFile:this.mediaFile,clickThrough:this.clickThrough,skipoffset:this.skipoffset},this.postrollsCount++);"start"!==b&&"end"!==b&&("linear"===d&&(this.allVastMIDROLLS[this.midrollsCount]={mediaFile:this.mediaFile,clickThrough:this.clickThrough,
skipoffset:this.skipoffset,timeOffset:b},this.midrollsCount++),"nonlinear"===d&&(this.allVastNONLINEARS[this.nonlinearsCount]={staticResource:this.staticResource,nonLinearClickThrough:this.nonLinearClickThrough,nonLinearClickTracking:this.nonLinearClickTracking,minSuggestedDuration:this.minSuggestedDuration,timeOffset:b},this.nonlinearsCount++))};PLAYER.Vast.prototype.initData=function(b){if(0<this.arrVAST.length)for(b=0;b<this.arrVAST.length;b++)this.vastObj[b]=this.arrVAST[b];this.videoPlayer.checkForPoints()};